"""changed models to reflect the proces of the app. added 2 questionnaire tables, 1 emotion table and 3 adjective tables

Revision ID: 1f169f4b464b
Revises: da1ae782c6c0
Create Date: 2023-07-31 19:32:51.701406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f169f4b464b'
down_revision = 'da1ae782c6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions-1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['user-emotions.id'], name=op.f('fk_questions-1_emotion_id_user-emotions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions-2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('adjective_id_1', sa.Integer(), nullable=True),
    sa.Column('adjective_id_2', sa.Integer(), nullable=True),
    sa.Column('adjective_id_3', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjective_id_1'], ['user-emotion-adjectives-1.id'], name=op.f('fk_questions-2_adjective_id_1_user-emotion-adjectives-1')),
    sa.ForeignKeyConstraint(['adjective_id_2'], ['user-emotion-adjectives-2.id'], name=op.f('fk_questions-2_adjective_id_2_user-emotion-adjectives-2')),
    sa.ForeignKeyConstraint(['adjective_id_3'], ['user-emotion-adjectives-3.id'], name=op.f('fk_questions-2_adjective_id_3_user-emotion-adjectives-3')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user-emotion-adjectives-1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('meter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['user-emotions.id'], name=op.f('fk_user-emotion-adjectives-1_emotion_id_user-emotions')),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questions-2.id'], name=op.f('fk_user-emotion-adjectives-1_questionnaire_id_questions-2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user-emotion-adjectives-2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('meter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['user-emotions.id'], name=op.f('fk_user-emotion-adjectives-2_emotion_id_user-emotions')),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questions-2.id'], name=op.f('fk_user-emotion-adjectives-2_questionnaire_id_questions-2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user-emotion-adjectives-3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('meter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['user-emotions.id'], name=op.f('fk_user-emotion-adjectives-3_emotion_id_user-emotions')),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questions-2.id'], name=op.f('fk_user-emotion-adjectives-3_questionnaire_id_questions-2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user-emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questions-1.id'], name=op.f('fk_user-emotions_questionnaire_id_questions-1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres-1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('meter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meter'], ['user-emotion-adjectives-1.meter'], name=op.f('fk_genres-1_meter_user-emotion-adjectives-1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres-2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('meter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meter'], ['user-emotion-adjectives-2.meter'], name=op.f('fk_genres-2_meter_user-emotion-adjectives-2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres-3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('meter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meter'], ['user-emotion-adjectives-3.meter'], name=op.f('fk_genres-3_meter_user-emotion-adjectives-3')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_1', sa.Integer(), nullable=True),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_2', sa.Integer(), nullable=True),
    sa.Column('adjective_1_id', sa.Integer(), nullable=True),
    sa.Column('adjective_2_id', sa.Integer(), nullable=True),
    sa.Column('adjective_3_id', sa.Integer(), nullable=True),
    sa.Column('genre_1_id', sa.Integer(), nullable=True),
    sa.Column('genre_2_id', sa.Integer(), nullable=True),
    sa.Column('genre_3_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjective_1_id'], ['user-emotion-adjectives-1.id'], name=op.f('fk_records_adjective_1_id_user-emotion-adjectives-1')),
    sa.ForeignKeyConstraint(['adjective_2_id'], ['user-emotion-adjectives-2.id'], name=op.f('fk_records_adjective_2_id_user-emotion-adjectives-2')),
    sa.ForeignKeyConstraint(['adjective_3_id'], ['user-emotion-adjectives-3.id'], name=op.f('fk_records_adjective_3_id_user-emotion-adjectives-3')),
    sa.ForeignKeyConstraint(['emotion_id'], ['user-emotions.id'], name=op.f('fk_records_emotion_id_user-emotions')),
    sa.ForeignKeyConstraint(['genre_1_id'], ['genres-1.id'], name=op.f('fk_records_genre_1_id_genres-1')),
    sa.ForeignKeyConstraint(['genre_2_id'], ['genres-2.id'], name=op.f('fk_records_genre_2_id_genres-2')),
    sa.ForeignKeyConstraint(['genre_3_id'], ['genres-3.id'], name=op.f('fk_records_genre_3_id_genres-3')),
    sa.ForeignKeyConstraint(['questionnaire_1'], ['questions-1.id'], name=op.f('fk_records_questionnaire_1_questions-1')),
    sa.ForeignKeyConstraint(['questionnaire_2'], ['questions-2.id'], name=op.f('fk_records_questionnaire_2_questions-2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('moods')
    op.drop_table('playlists')
    op.drop_table('artist')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('question', sa.VARCHAR(), nullable=True),
    sa.Column('mood_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], name='fk_questions_mood_id_moods'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_questions_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('questionnaire', sa.INTEGER(), nullable=True),
    sa.Column('mood', sa.INTEGER(), nullable=True),
    sa.Column('playlist', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mood'], ['moods.id'], name='fk_users_mood_moods'),
    sa.ForeignKeyConstraint(['playlist'], ['playlists.id'], name='fk_users_playlist_playlists'),
    sa.ForeignKeyConstraint(['questionnaire'], ['questions.id'], name='fk_users_questionnaire_questions'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('artist_id', sa.INTEGER(), nullable=True),
    sa.Column('mood_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], name='fk_artist_mood_id_moods'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('mood_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], name='fk_playlists_mood_id_moods'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('mood', sa.VARCHAR(), nullable=True),
    sa.Column('mood_score', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_moods_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('records')
    op.drop_table('genres-3')
    op.drop_table('genres-2')
    op.drop_table('genres-1')
    op.drop_table('user-emotions')
    op.drop_table('user-emotion-adjectives-3')
    op.drop_table('user-emotion-adjectives-2')
    op.drop_table('user-emotion-adjectives-1')
    op.drop_table('questions-2')
    op.drop_table('questions-1')
    # ### end Alembic commands ###
