"""created user, mood, questionnare, and playlist models

Revision ID: beb077cc09af
Revises: 
Create Date: 2023-07-26 12:20:01.141915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb077cc09af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_moods_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], name=op.f('fk_playlists_mood_id_moods')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], name=op.f('fk_questions_mood_id_moods')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_questions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('questionnaire', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('playlist', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mood'], ['moods.id'], name=op.f('fk_users_mood_moods')),
    sa.ForeignKeyConstraint(['playlist'], ['playlists.id'], name=op.f('fk_users_playlist_playlists')),
    sa.ForeignKeyConstraint(['questionnaire'], ['questions.id'], name=op.f('fk_users_questionnaire_questions')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_table('playlists')
    op.drop_table('moods')
    # ### end Alembic commands ###
