"""added a artistmood join table 

Revision ID: da1ae782c6c0
Revises: beb077cc09af
Create Date: 2023-07-28 13:37:42.803793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1ae782c6c0'
down_revision = 'beb077cc09af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], name=op.f('fk_artist_mood_id_moods')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.drop_column('mood_score')

    op.drop_table('artist')
    # ### end Alembic commands ###
